/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib_projekt;
import oru.inf.InfDB;
import oru.inf.InfException; 

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;


        
/**
 *
 * @author David
 */
public class AndraOmradesChef extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form AndraOmradesChef
     */
    public AndraOmradesChef() {
        initComponents();
              try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            System.out.println("funka");
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAgentID = new javax.swing.JLabel();
        jlOmrade = new javax.swing.JLabel();
        jlAndraOmradesChef = new javax.swing.JLabel();
        ValjOmradeCBox = new javax.swing.JComboBox<>();
        jtxtAgentID = new javax.swing.JTextField();
        jbGodkanAndring = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlAgentID.setText("Agent ID");

        jlOmrade.setText("Område");

        jlAndraOmradesChef.setText("Andra Områdeschef");

        ValjOmradeCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Svealand", "Götaland", "Norrland" }));

        jtxtAgentID.setText("Skriv in Agent ID");
        jtxtAgentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAgentIDActionPerformed(evt);
            }
        });

        jbGodkanAndring.setText("godkän ändring");
        jbGodkanAndring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGodkanAndringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGodkanAndring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlAndraOmradesChef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ValjOmradeCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAgentID))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlAgentID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlOmrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValjOmradeCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlAndraOmradesChef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGodkanAndring)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtAgentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAgentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAgentIDActionPerformed

    private void jbGodkanAndringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGodkanAndringActionPerformed
    // Andra omdrådeschef 
        if (jtxtAgentID.getText().isEmpty() || ValjOmradeCBox.getSelectedItem().toString().isEmpty()) {
        // Om någon av textrutorna är tom, visa felmeddelande
        JOptionPane.showMessageDialog(null, "Du måste skriva in rätt AgentID och välja rätt område");
        jtxtAgentID.requestFocus();
        } else{
            try{
                
                String agentID = jtxtAgentID.getText();
                String omrade = ValjOmradeCBox.getSelectedItem().toString();
                
                if (!agentID.isEmpty()){  
                    String omradesID = idb.fetchSingle("SELECT Omrades_ID FROM omrade WHERE benamning =" + "'" + omrade + "'");
               
                    // Uppdaterar den nya områdeschefen
                    idb.update("UPDATE omradeschef SET agent_ID = " + agentID + ", omrade = " + "'" + omradesID + "'" + "WHERE omrade = '" + omradesID + "'");
                    // Meddalar användaren att ändringen är lyckad
                    JOptionPane.showMessageDialog(null, "Områdeschefen har nu lyckats ändrats");
                }
            } catch (InfException e) {
                //Om något annat fel visas detta.
            JOptionPane.showMessageDialog(null, "Hoppsan, något gick fel!");
            System.out.println("Internt felmeddelande" + e.getMessage());
            }
        }
    }//GEN-LAST:event_jbGodkanAndringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraOmradesChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraOmradesChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraOmradesChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraOmradesChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AndraOmradesChef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ValjOmradeCBox;
    private javax.swing.JButton jbGodkanAndring;
    private javax.swing.JLabel jlAgentID;
    private javax.swing.JLabel jlAndraOmradesChef;
    private javax.swing.JLabel jlOmrade;
    private javax.swing.JTextField jtxtAgentID;
    // End of variables declaration//GEN-END:variables
}
