/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib_projekt;

import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author David
 */
public class GeAgentAdminstatus extends javax.swing.JFrame {
    private InfDB idb;

            
    /**
     * Creates new form GeAgentAdminstatus
     */
    public GeAgentAdminstatus(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllAgentNamn(); 
        fyllAdminStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxValjAgent = new javax.swing.JComboBox<>();
        ComboBoxValjStatus = new javax.swing.JComboBox<>();
        lblValjAgent = new javax.swing.JLabel();
        lbValjStatus = new javax.swing.JLabel();
        lblAndraAdminStatus = new javax.swing.JLabel();
        btnGodkann = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTillbaka2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValjAgent.setText("Välj Agent");

        lbValjStatus.setText("Välj vilken status du vill tilldela agenten");

        lblAndraAdminStatus.setText("Ändra Administratörstatus");

        btnGodkann.setText("Godkänn ändring");
        btnGodkann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGodkannActionPerformed(evt);
            }
        });

        btnTillbaka2.setText("Tillbaka");
        btnTillbaka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbaka2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(lbValjStatus)
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAndraAdminStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbaka2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(ComboBoxValjStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnGodkann)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAndraAdminStatus)
                    .addComponent(btnTillbaka2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValjAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbValjStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxValjStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGodkann)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void fyllAgentNamn(){
        try {
            // SQL-fråga för att hämta Plats_ID och Benamning från plats-tabellen
            String fraga = "SELECT Agent_ID, Namn FROM agent;";
            // Utför SQL-frågan och få resultatet
            var resultat = idb.fetchRows(fraga);

            // Iterera över varje rad i resultatet
            for (HashMap<String, String> rad : resultat) {
                // Hämta Plats_ID och Benamning från raden
                String AgentIdStr = rad.get("Agent_ID");
                String AgentNamn = rad.get("Namn");

                // Kontrollera om Plats_ID är inte null
                if (AgentIdStr != null) {
                    // Lägg till Benamning i dropdown-menyn
                    ComboBoxValjAgent.addItem(AgentNamn);
                }
            }
        } catch (InfException ex) {
            // Visa felmeddelande om något går fel med databasen
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }
    
    private void fyllAdminStatus(){
            ComboBoxValjStatus.addItem("J");
            ComboBoxValjStatus.addItem("N");
    }

    private void btnGodkannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGodkannActionPerformed
    try {
 
        String valdAgentNamn = ComboBoxValjAgent.getSelectedItem().toString();

        if (valdAgentNamn != null) {
            // Hämta aktuell adminstatus för den valda agenten
            String fraga = "SELECT Administrator FROM agent WHERE Namn = '" + valdAgentNamn + "'";
            String aktuellAdminStatus = idb.fetchSingle(fraga);

            // Byt adminstatus
            String nyAdminStatus = "N";
            if ("N".equals(aktuellAdminStatus)) {
                nyAdminStatus = "J";
            }

            // Uppdatera adminstatus för den valda agenten i databasen
            String updateFraga = "UPDATE agent SET Administrator = '" + nyAdminStatus + "' WHERE Namn = '" + valdAgentNamn + "'";
            idb.update(updateFraga);
            JOptionPane.showMessageDialog(null, "Ändring Lyckades!");
        }
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Något gick fel med SQL-frågan!");
        System.out.println("Internt felmeddelande: " + e.getMessage());
    }
    }//GEN-LAST:event_btnGodkannActionPerformed

    private void btnTillbaka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbaka2ActionPerformed
        // TODO add your handling code here:
        EfterInloggAdmin nytt = new EfterInloggAdmin();
        GeAgentAdminstatus.this.setVisible(false);
        nytt.setVisible(true);
    }//GEN-LAST:event_btnTillbaka2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try{
            InfDB idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            GeAgentAdminstatus GeAgentAdminstatusFrame = new GeAgentAdminstatus(idb); 
            
        
            GeAgentAdminstatusFrame.setSize(551, 301);
            GeAgentAdminstatusFrame.setVisible(true);
        } catch (InfException Fel) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande: " + Fel.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxValjAgent;
    private javax.swing.JComboBox<String> ComboBoxValjStatus;
    private javax.swing.JButton btnGodkann;
    private javax.swing.JButton btnTillbaka2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbValjStatus;
    private javax.swing.JLabel lblAndraAdminStatus;
    private javax.swing.JLabel lblValjAgent;
    // End of variables declaration//GEN-END:variables
}
